[package]
name = "file_rat"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
bzip2 = "0.4.4"
memmap2 = "0.9.4"
tempfile = "3.10.1"

[dependencies.uuid]
version = "1.3.1"
features = ["v1", "rng" , "serde"]

[dependencies.serde]
version = "1.0.203"
features = ["derive"]